### ISSUE TITLE
[DISCUSSION] SwiftLint 룰 재정의 건의 

### ISSUE THREAD

**Issue by ericKwon95** [TheClimeet/climeet-iOS#36]
## 개요
- 현재 작성되어 있는 SwiftLint 룰셋 재정의를 건의합니다.

## 문제 상황
- 현재 정의된 SwiftLint 룰은 아래와 같습니다.
```yml
only_rules:
  # colon 스타일, 암시적 옵셔널, 구형 함수, 연산자 사용 시 공백, 불필요한 선택적 바인딩, 수직 공백 등 특정한 SwiftLint 규칙만 적용
  - colon                        # 콜론(:) 스타일 규칙 적용
  - fatal_error_message           # fatalError 호출 시 메시지 필수 규칙 적용
  - implicitly_unwrapped_optional # 암시적 옵셔널 사용 방지 규칙 적용
  - legacy_cggeometry_functions   # 구형 CoreGraphics Geometry 함수 사용 방지 규칙 적용
  - legacy_constant               # 구형 상수(Deprecated) 사용 방지 규칙 적용
  - legacy_constructor            # 구형 생성자 사용 방지 규칙 적용
  - legacy_nsgeometry_functions   # 구형 NSGeometry 함수 사용 방지 규칙 적용
  - operator_usage_whitespace      # 연산자 사용 시 공백 규칙 적용
  - return_arrow_whitespace        # return 화살표(->) 주변 공백 규칙 적용
  - trailing_newline               # 파일 마지막에 줄바꿈이 있어야 하는 규칙 적용
  - unused_optional_binding        # 사용되지 않는 선택적 바인딩 방지 규칙 적용
  - vertical_whitespace            # 수직 공백 규칙 적용 (코드 블록 사이의 불필요한 공백 방지)
  - void_return                    # 반환 타입으로 'Void' 사용 시 일관된 스타일 적용
  - unowned_variable_capture       # unowned 변수 캡처 시 주의 필요 규칙 적용
  - custom_rules                   # 사용자 정의 규칙 추가

excluded:
  # 특정 디렉토리 (Carthage, Pods, .build)는 SwiftLint 검사에서 제외
  - Carthage
  - Pods
  - .build

colon:
  apply_to_dictionaries: false  # 딕셔너리 타입에 대해서는 콜론(:) 스타일 규칙 적용 안함

indentation: 2  # 들여쓰기를 2칸으로 설정

custom_rules:  
  no_objcMembers:  # @objcMembers 사용 방지 규칙
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Objective-C로 노출할 멤버에 대해서는 명시적으로 @objc를 사용하십시오."
    severity: error  # 이 규칙을 위반하면 오류로 처리

#  no_direct_standard_out_logs:  # 표준 출력에 로그를 직접 작성하는 것을 금지하는 규칙 (현재 비활성화 상태)
#    name: "Writing log messages directly to standard out is disallowed"
#    regex: "(\\bprint|\\bdebugPrint|\\bdump|Swift\\.print|Swift\\.debugPrint|Swift\\.dump)\\s*\\("
    match_kinds:
    - identifier
    message: "로그 메시지를 표준 출력으로 직접 작성하지 마십시오. 전용 로깅 시스템을 사용하거나 디버그 전용 시나리오에서 이 경고를 명시적으로 비활성화하십시오."
    severity: error  # 이 규칙을 위반하면 오류로 처리

  no_file_literal:  # #file 사용 금지 규칙
    name: "#file is disallowed"
    regex: "(\\b#file\\b)"
    match_kinds:
    - identifier
    message: "대신 #fileID를 사용하십시오."
    severity: error  # 이 규칙을 위반하면 오류로 처리

  no_filepath_literal:  # #filePath 사용 금지 규칙
    name: "#filePath is disallowed"
    regex: "(\\b#filePath\\b)"
    match_kinds:
    - identifier
    message: "대신 #fileID를 사용하십시오."
    severity: error  # 이 규칙을 위반하면 오류로 처리

  no_unchecked_sendable:  # @unchecked Sendable 사용 방지 규칙
    name: "`@unchecked Sendable` is discouraged."
    regex: "@unchecked Sendable"
    match_kinds:
    - attribute.builtin
    - typeidentifier
    message: "대신 안전한 대안을 고려하십시오. 필요한 경우 명시적으로 주석을 달아 이 경고를 비활성화할 수 있습니다."
    severity: error  # 이 규칙을 위반하면 오류로 처리
```
- @objcMembers, #file 사용 금지 등 현재 프로젝트에서는 불필요하다고 생각되는 룰도 있고 (혹시 제가 잘못 생각했다면 알려주세요!)
- no_direct_standard_out_logs 룰 같은 경우엔 비활성화 되어 있는 등 팀 목적에 맞게 유지보수 되지 않고 있다는 생각이 들었습니다!
- 강제 옵셔널 언래핑 방지와 공백 등 현재 팀에서 필요하다고 생각하는 규칙 위주로 업데이트를 하는 것이 장기적 유지보수 측면에서 좋을 것이라고 생각됩니다. 

## 해결 방안 제시
- 현재 제가 생각한 필수적인 SwiftLint 룰은 아래와 같습니다:
  - 강제 언래핑 방지 룰
  - 코드 컨벤션을 맞추기 위한 공백 관련 룰
- 추가하고 싶거나 필요하다고 생각되는 룰, 또는 제가 생각한 룰이 필요하지 않다고 생각되는 등의 논의를 이어가며 저희만의 SwiftLint 규칙을 만들어가 보는 것은 어떨까 건의드립니다!
- 또는 이미 만들어진 검증된 컨벤션을 확인 및 따라해 보며 룰을 수정해 나가는 것도 좋다고 생각합니다.

## 기타 사항
- [SwiftLint Rule Documentation](https://realm.github.io/SwiftLint/rule-directory.html)을 참고해 어떤 규칙이 있는지 확인할 수 있습니다.
